name: Auto-merge Codex PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: >-
      contains(github.event.pull_request.labels.*.name, 'codex') ||
      github.event.pull_request.user.login == 'lrpthomas'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
