on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  enable-auto-merge:
    if: >
      contains(github.event.pull_request.labels.*.name, 'codex') ||
      github.event.pull_request.user.login == 'lrpthomas'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Check if PR is mergeable
        id: mergeable
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            core.setOutput('mergeable', pr.data.mergeable);

      - name: Enable Auto-Merge
        if: steps.mergeable.outputs.mergeable == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
