name: Auto-merge Codex PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-auto-merge:
    if: >-
      contains(github.event.pull_request.labels.*.name, 'codex') ||
      github.event.pull_request.user.login == 'lrpthomas'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Wait for all checks to complete
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const head_sha = pr.head.sha;
            let checksCompleted = false;
            let maxAttempts = 30; // wait up to 10 minutes (30 x 20s)
            let attempt = 0;
            while (!checksCompleted && attempt < maxAttempts) {
              const { data: checkRuns } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: head_sha,
              });
              const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: head_sha,
              });
              const allChecks = checkRuns.check_runs.concat(statuses);
              checksCompleted = allChecks.every(c =>
                (c.status === 'completed' || c.state === 'success' || c.state === 'failure')
              );
              if (!checksCompleted) {
                core.info('Not all checks are complete. Waiting 20 seconds...');
                await new Promise(res => setTimeout(res, 20000));
                attempt++;
              }
            }
            if (!checksCompleted) {
              core.setFailed('Timed out waiting for all checks to complete.');
            }

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
